### ISSUE TITLE
Manage global Store in an Android application

### ISSUE THREAD

**Issue by sunilson** [brianegan/bansa#27]
Hi,

I am currently learning to implement a small Android app with this library, but I am unsure where you would put the Store. Should there really be an application wide store Singleton and how would I handle orientation changes or the Android system killing the process and saving/restoring the state? Or is it better to put the store inside the ViewModel of the Android Architecture Components?

Thanks for your input!

**Comment by brianegan** [comment]
Unfortunately, I'm not too sure, and I'd actually recommend against using this lib. I'm not actively maintaining this project any longer and I've moved away from Android development over the past year.

A better alternative would be something like [Reduks](https://github.com/beyondeye/Reduks/tree/3.x_kotlin_1_1) which has a built-in solution to that problem.

**Comment by sunilson** [comment]
Ok, thanks for your answer!
